// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2qltGrnGaM5PNBQ4kk0yzCZP6clSGKE',
    appId: '1:764536150954:web:d7d681df4af9deccfb69d3',
    messagingSenderId: '764536150954',
    projectId: 'flutter-chat-app-1191b',
    authDomain: 'flutter-chat-app-1191b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1191b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDN-jmck-RhYcCxurxLINOQoio4ZtlcRY',
    appId: '1:764536150954:android:12917476a3f48daffb69d3',
    messagingSenderId: '764536150954',
    projectId: 'flutter-chat-app-1191b',
    storageBucket: 'flutter-chat-app-1191b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwr0rSofixK5i_Q4mIwm1D68RJmUqBQlM',
    appId: '1:764536150954:ios:4539ba26808ecef7fb69d3',
    messagingSenderId: '764536150954',
    projectId: 'flutter-chat-app-1191b',
    storageBucket: 'flutter-chat-app-1191b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
